version: "2"
services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    networks:
      - webappnetwork
    volumes:
      - app:/app
      - app:/app/node_modules
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
volumes:
  app: